name: driver_app
description: "Driver location tracking app for waste collection vehicles."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ===== BACKGROUND SERVICE =====
  flutter_background_service: ^5.0.0

  # ===== FIREBASE =====
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.17.9

  # ===== LOCATION + PERMISSIONS =====
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

  # ===== STORAGE =====
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3

  # ===== DEVICE INFO & BATTERY =====
  device_info_plus: ^10.1.0
  battery_plus: ^5.0.2
  connectivity_plus: ^5.0.2

  # ===== MAP =====
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.1

  # ===== UI & Icons =====
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # ===== APP ICON GENERATOR =====
  flutter_launcher_icons: ^0.13.1

# ===== APP ICON CONFIGURATION =====
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon_foreground.png"


flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/app_icon_foreground.png
